name: Publish Docs

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Which target to build'
        type: choice
        options:
        - all-documentation
        - image-based-video-search
        - loitering-detection
        - pallet-defect-detection
        - pcb-anomaly-detection
        - robotics-ai-suite
        - smart-parking
        - smart-intersection
        - weld-porosity
        - wind-turbine-anomaly-detection
        - worker-safety-gear-detection

permissions: {}

jobs:
  build_image-based-video-search:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'image-based-video-search') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/image-based-video-search

  build_loitering-detection:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'loitering-detection') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/metro-vision-ai-app-recipe/loitering-detection

  build_pallet-defect-detection:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'pallet-defect-detection') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-vision/apps/pallet-defect-detection

  build_pcb-anomaly-detection:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'pcb-anomaly-detection') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-vision/apps/pcb-anomaly-detection
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it

  build_robotics-ai-suite:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'robotics-ai-suite') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: robotics-ai-suite
      simple_mode: false
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it

  build_smart-intersection:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'smart-intersection') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/metro-vision-ai-app-recipe/smart-intersection
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it
  
  build_smart-parking:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'smart-parking') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: metro-ai-suite/metro-vision-ai-app-recipe/smart-parking

  build_weld-porosity:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'weld-porosity') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-vision/apps/weld-porosity

  build_wind-turbine-anomaly-detection:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'wind-turbine-anomaly-detection') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/wind-turbine-anomaly-detection
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it

  build_worker-safety-gear-detection:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    if: ${{ (github.event.inputs.target == 'worker-safety-gear-detection') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@32469fcb74db17f617e237012104e3b2f1c2da2e
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: manufacturing-ai-suite/industrial-edge-insights-vision/apps/worker-safety-gear-detection
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it
